from pyalpha.definition.register_names import *
from pyalpha.definition.register_values import *

modbus_map = {
    # Device Information
    device_sn_n: device_sn,

    # Summary Registers
    work_mode_n: work_mode,
    work_status_n: work_status,
    system_total_rated_power_n: system_total_rated_power,
    system_chargeable_energy_n: system_chargeable_energy,
    system_dischargeable_energy_n: system_dischargeable_energy,
    system_chargeable_power_n: system_chargeable_power,
    system_dischargeable_power_n: system_dischargeable_power,
    max_power_charge_available_time_n: max_power_charge_available_time,
    max_power_discharge_available_time_n: max_power_discharge_available_time,
    system_soc_n: system_soc,
    system_active_power_n: system_active_power,
    system_reactive_power_n: system_reactive_power,
    system_total_charge_n: system_total_charge,
    system_total_discharge_n: system_total_discharge,
    system_daily_charge_n: system_daily_charge,
    system_daily_discharge_n: system_daily_discharge,
    available_reactive_power_n: available_reactive_power,
    total_power_generation_n: total_power_generation,
    daily_power_generation_n: daily_power_generation,
    pv_installed_capacity_n: pv_installed_capacity,
    pv_theoretical_active_power_n: pv_theoretical_active_power,
    pv_available_active_power_n: pv_available_active_power,
    pv_available_reactive_power_n: pv_available_reactive_power,
    pv_active_power_n: pv_active_power,
    pv_reactive_power_n: pv_reactive_power,
    grid_side_load_total_power_n: grid_side_load_total_power,
    backup_side_load_total_power_n: backup_side_load_total_power,
    total_load_power_n: total_load_power,
    total_battery_power_n: total_battery_power,
    platform_type_n: platform_type,
    protocol_version_n: protocol_version,
    dual_power_state_n: dual_power_state,
    system_mode_n: system_mode,

    # Grid Gateway Meter
    grid_meter_a_voltage_n: grid_meter_a_voltage,
    grid_meter_b_voltage_n: grid_meter_b_voltage,
    grid_meter_c_voltage_n: grid_meter_c_voltage,
    grid_meter_a_current_n: grid_meter_a_current,
    grid_meter_b_current_n: grid_meter_b_current,
    grid_meter_c_current_n: grid_meter_c_current,
    grid_meter_frequency_n: grid_meter_frequency,
    grid_meter_total_pf_n: grid_meter_total_pf,
    grid_meter_a_active_power_n: grid_meter_a_active_power,
    grid_meter_b_active_power_n: grid_meter_b_active_power,
    grid_meter_c_active_power_n: grid_meter_c_active_power,
    grid_meter_a_apparent_power_n: grid_meter_a_apparent_power,
    grid_meter_b_apparent_power_n: grid_meter_b_apparent_power,
    grid_meter_c_apparent_power_n: grid_meter_c_apparent_power,
    grid_meter_total_active_power_n: grid_meter_total_active_power,
    grid_meter_total_reactive_power_n: grid_meter_total_reactive_power,
    grid_meter_total_apparent_power_n: grid_meter_total_apparent_power,
    grid_meter_positive_energy_n: grid_meter_positive_energy,
    grid_meter_reverse_energy_n: grid_meter_reverse_energy,
    grid_meter_max_demand_n: grid_meter_max_demand,
    grid_meter_comm_status_n: grid_meter_comm_status,
    grid_meter_ct_ratio_n: grid_meter_ct_ratio,
    grid_meter_pt_ratio_n: grid_meter_pt_ratio,

    # Diesel Generator Meter
    dg_meter_a_voltage_n: dg_meter_a_voltage,
    dg_meter_b_voltage_n: dg_meter_b_voltage,
    dg_meter_c_voltage_n: dg_meter_c_voltage,
    dg_meter_a_current_n: dg_meter_a_current,
    dg_meter_b_current_n: dg_meter_b_current,
    dg_meter_c_current_n: dg_meter_c_current,
    dg_meter_frequency_n: dg_meter_frequency,
    dg_meter_total_pf_n: dg_meter_total_pf,
    dg_meter_a_active_power_n: dg_meter_a_active_power,
    dg_meter_b_active_power_n: dg_meter_b_active_power,
    dg_meter_c_active_power_n: dg_meter_c_active_power,
    dg_meter_a_apparent_power_n: dg_meter_a_apparent_power,
    dg_meter_b_apparent_power_n: dg_meter_b_apparent_power,
    dg_meter_c_apparent_power_n: dg_meter_c_apparent_power,
    dg_meter_total_active_power_n: dg_meter_total_active_power,
    dg_meter_total_reactive_power_n: dg_meter_total_reactive_power,
    dg_meter_total_apparent_power_n: dg_meter_total_apparent_power,
    dg_meter_positive_energy_n: dg_meter_positive_energy,
    dg_meter_reverse_energy_n: dg_meter_reverse_energy,
    dg_meter_max_demand_n: dg_meter_max_demand,
    dg_meter_comm_status_n: dg_meter_comm_status,
    dg_meter_ct_ratio_n: dg_meter_ct_ratio,
    dg_meter_pt_ratio_n: dg_meter_pt_ratio,

    # PV Grid-tie Meter
    pv_meter_a_voltage_n: pv_meter_a_voltage,
    pv_meter_b_voltage_n: pv_meter_b_voltage,
    pv_meter_c_voltage_n: pv_meter_c_voltage,
    pv_meter_a_current_n: pv_meter_a_current,
    pv_meter_b_current_n: pv_meter_b_current,
    pv_meter_c_current_n: pv_meter_c_current,
    pv_meter_frequency_n: pv_meter_frequency,
    pv_meter_total_pf_n: pv_meter_total_pf,
    pv_meter_a_active_power_n: pv_meter_a_active_power,
    pv_meter_b_active_power_n: pv_meter_b_active_power,
    pv_meter_c_active_power_n: pv_meter_c_active_power,
    pv_meter_a_apparent_power_n: pv_meter_a_apparent_power,
    pv_meter_b_apparent_power_n: pv_meter_b_apparent_power,
    pv_meter_c_apparent_power_n: pv_meter_c_apparent_power,
    pv_meter_total_active_power_n: pv_meter_total_active_power,
    pv_meter_total_reactive_power_n: pv_meter_total_reactive_power,
    pv_meter_total_apparent_power_n: pv_meter_total_apparent_power,
    pv_meter_positive_energy_n: pv_meter_positive_energy,
    pv_meter_reverse_energy_n: pv_meter_reverse_energy,
    pv_meter_max_demand_n: pv_meter_max_demand,
    pv_meter_comm_status_n: pv_meter_comm_status,
    pv_meter_ct_ratio_n: pv_meter_ct_ratio,
    pv_meter_pt_ratio_n: pv_meter_pt_ratio,

    # PV Inverter (n=1)
    pv_inverter_active_regulator_n: pv_inverter_active_regulator,
    pv_inverter_a_voltage_n: pv_inverter_a_voltage,
    pv_inverter_b_voltage_n: pv_inverter_b_voltage,
    pv_inverter_c_voltage_n: pv_inverter_c_voltage,
    pv_inverter_frequency_n: pv_inverter_frequency,
    pv_inverter_daily_energy_n: pv_inverter_daily_energy,
    pv_inverter_active_power_n: pv_inverter_active_power,
    pv_inverter_work_mode_n: pv_inverter_work_mode,
    pv_inverter_temperature_n: pv_inverter_temperature,
    pv_inverter_total_energy_n: pv_inverter_total_energy,
    pv_inverter_fault1_n: pv_inverter_fault1,
    pv_inverter_fault2_n: pv_inverter_fault2,
    pv_inverter_comm_status_n: pv_inverter_comm_status,
    pv_inverter_real_comm_status_n: pv_inverter_real_comm_status,

    # Control Registers
    ctrl_active_power_setpoint_n: ctrl_active_power_setpoint,
    ctrl_reactive_power_setpoint_n: ctrl_reactive_power_setpoint,
    ctrl_dispatch_timeout_n: ctrl_dispatch_timeout,
    ctrl_dispatch_interrupt_mode_n: ctrl_dispatch_interrupt_mode,
    ctrl_on_off_command_n: ctrl_on_off_command,
    ctrl_fault_clearance_n: ctrl_fault_clearance,
    ctrl_ems_mode_n: ctrl_ems_mode,
}
