from pyalpha.definition.models import ModbusRegister, ModbusType, ModbusUnit

device_sn = ModbusRegister(10000, 8, 3, ModbusType.STRING, ModbusUnit.NONE, gain=1)

# Summary Registers (function code 3, addresses 0-61)
work_mode = ModbusRegister(0, 1, 3, ModbusType.U16, ModbusUnit.NONE)
work_status = ModbusRegister(1, 1, 3, ModbusType.U16, ModbusUnit.NONE)
system_total_rated_power = ModbusRegister(2, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
system_chargeable_energy = ModbusRegister(4, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=0.1)
system_dischargeable_energy = ModbusRegister(6, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=0.1)
system_chargeable_power = ModbusRegister(8, 2, 3, ModbusType.U32, ModbusUnit.KW, gain=0.1)
system_dischargeable_power = ModbusRegister(10, 2, 3, ModbusType.U32, ModbusUnit.KW, gain=0.1)
max_power_charge_available_time = ModbusRegister(12, 1, 3, ModbusType.U16, ModbusUnit.MINUTE)
max_power_discharge_available_time = ModbusRegister(13, 1, 3, ModbusType.U16, ModbusUnit.MINUTE)
system_soc = ModbusRegister(14, 1, 3, ModbusType.U16, ModbusUnit.PERCENTAGE, gain=0.1)
system_active_power = ModbusRegister(19, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
system_reactive_power = ModbusRegister(21, 2, 3, ModbusType.S32, ModbusUnit.KVAR, gain=0.1)
system_total_charge = ModbusRegister(23, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=10)
system_total_discharge = ModbusRegister(25, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=10)
system_daily_charge = ModbusRegister(27, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=0.1)
system_daily_discharge = ModbusRegister(29, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=0.1)
available_reactive_power = ModbusRegister(31, 2, 3, ModbusType.U32, ModbusUnit.KVAR, gain=0.1)
total_power_generation = ModbusRegister(33, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=10)
daily_power_generation = ModbusRegister(35, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=0.1)
pv_installed_capacity = ModbusRegister(37, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=0.1)
pv_theoretical_active_power = ModbusRegister(39, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
pv_available_active_power = ModbusRegister(41, 2, 3, ModbusType.U32, ModbusUnit.KW, gain=0.1)
pv_available_reactive_power = ModbusRegister(43, 2, 3, ModbusType.U32, ModbusUnit.KVAR, gain=0.1)
pv_active_power = ModbusRegister(45, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
pv_reactive_power = ModbusRegister(47, 2, 3, ModbusType.S32, ModbusUnit.KVAR, gain=0.1)
grid_side_load_total_power = ModbusRegister(49, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
backup_side_load_total_power = ModbusRegister(51, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
total_load_power = ModbusRegister(53, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
total_battery_power = ModbusRegister(55, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
platform_type = ModbusRegister(57, 1, 3, ModbusType.U16, ModbusUnit.NONE)
protocol_version = ModbusRegister(58, 1, 3, ModbusType.U16, ModbusUnit.NONE)
dual_power_state = ModbusRegister(59, 1, 3, ModbusType.U16, ModbusUnit.NONE)
system_mode = ModbusRegister(60, 1, 3, ModbusType.U16, ModbusUnit.NONE)

# Meter Registers - Grid Gateway Meter (100-140)
grid_meter_a_voltage = ModbusRegister(100, 2, 3, ModbusType.S32, ModbusUnit.VOLT, gain=0.1)
grid_meter_b_voltage = ModbusRegister(102, 2, 3, ModbusType.S32, ModbusUnit.VOLT, gain=0.1)
grid_meter_c_voltage = ModbusRegister(104, 2, 3, ModbusType.S32, ModbusUnit.VOLT, gain=0.1)
grid_meter_a_current = ModbusRegister(106, 2, 3, ModbusType.S32, ModbusUnit.AMPERE, gain=0.1)
grid_meter_b_current = ModbusRegister(108, 2, 3, ModbusType.S32, ModbusUnit.AMPERE, gain=0.1)
grid_meter_c_current = ModbusRegister(110, 2, 3, ModbusType.S32, ModbusUnit.AMPERE, gain=0.1)
grid_meter_frequency = ModbusRegister(112, 1, 3, ModbusType.U16, ModbusUnit.HERTZ, gain=0.001)
grid_meter_total_pf = ModbusRegister(113, 1, 3, ModbusType.S16, ModbusUnit.PF, gain=0.01)
grid_meter_a_active_power = ModbusRegister(114, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
grid_meter_b_active_power = ModbusRegister(116, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
grid_meter_c_active_power = ModbusRegister(118, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
grid_meter_a_apparent_power = ModbusRegister(120, 2, 3, ModbusType.S32, ModbusUnit.KVA, gain=0.1)
grid_meter_b_apparent_power = ModbusRegister(122, 2, 3, ModbusType.S32, ModbusUnit.KVA, gain=0.1)
grid_meter_c_apparent_power = ModbusRegister(124, 2, 3, ModbusType.S32, ModbusUnit.KVA, gain=0.1)
grid_meter_total_active_power = ModbusRegister(126, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
grid_meter_total_reactive_power = ModbusRegister(128, 2, 3, ModbusType.S32, ModbusUnit.KVAR, gain=0.1)
grid_meter_total_apparent_power = ModbusRegister(130, 2, 3, ModbusType.S32, ModbusUnit.KVA, gain=0.1)
grid_meter_positive_energy = ModbusRegister(132, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=0.01)
grid_meter_reverse_energy = ModbusRegister(134, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=0.01)
grid_meter_max_demand = ModbusRegister(136, 2, 3, ModbusType.U32, ModbusUnit.KW, gain=0.1)
grid_meter_comm_status = ModbusRegister(138, 1, 3, ModbusType.S16, ModbusUnit.NONE)
grid_meter_ct_ratio = ModbusRegister(139, 1, 3, ModbusType.S16, ModbusUnit.NONE)
grid_meter_pt_ratio = ModbusRegister(140, 1, 3, ModbusType.U16, ModbusUnit.NONE)

# Meter Registers - Diesel Generator Meter (160-200)
dg_meter_a_voltage = ModbusRegister(160, 2, 3, ModbusType.S32, ModbusUnit.VOLT, gain=0.1)
dg_meter_b_voltage = ModbusRegister(162, 2, 3, ModbusType.S32, ModbusUnit.VOLT, gain=0.1)
dg_meter_c_voltage = ModbusRegister(164, 2, 3, ModbusType.S32, ModbusUnit.VOLT, gain=0.1)
dg_meter_a_current = ModbusRegister(166, 2, 3, ModbusType.S32, ModbusUnit.AMPERE, gain=0.1)
dg_meter_b_current = ModbusRegister(168, 2, 3, ModbusType.S32, ModbusUnit.AMPERE, gain=0.1)
dg_meter_c_current = ModbusRegister(170, 2, 3, ModbusType.S32, ModbusUnit.AMPERE, gain=0.1)
dg_meter_frequency = ModbusRegister(172, 1, 3, ModbusType.U16, ModbusUnit.HERTZ, gain=0.001)
dg_meter_total_pf = ModbusRegister(173, 1, 3, ModbusType.S16, ModbusUnit.PF, gain=0.01)
dg_meter_a_active_power = ModbusRegister(174, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
dg_meter_b_active_power = ModbusRegister(176, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
dg_meter_c_active_power = ModbusRegister(178, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
dg_meter_a_apparent_power = ModbusRegister(180, 2, 3, ModbusType.S32, ModbusUnit.KVA, gain=0.1)
dg_meter_b_apparent_power = ModbusRegister(182, 2, 3, ModbusType.S32, ModbusUnit.KVA, gain=0.1)
dg_meter_c_apparent_power = ModbusRegister(184, 2, 3, ModbusType.S32, ModbusUnit.KVA, gain=0.1)
dg_meter_total_active_power = ModbusRegister(186, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
dg_meter_total_reactive_power = ModbusRegister(188, 2, 3, ModbusType.S32, ModbusUnit.KVAR, gain=0.1)
dg_meter_total_apparent_power = ModbusRegister(190, 2, 3, ModbusType.S32, ModbusUnit.KVA, gain=0.1)
dg_meter_positive_energy = ModbusRegister(192, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=0.01)
dg_meter_reverse_energy = ModbusRegister(194, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=0.01)
dg_meter_max_demand = ModbusRegister(196, 2, 3, ModbusType.U32, ModbusUnit.KW, gain=0.1)
dg_meter_comm_status = ModbusRegister(198, 1, 3, ModbusType.S16, ModbusUnit.NONE)
dg_meter_ct_ratio = ModbusRegister(199, 1, 3, ModbusType.S16, ModbusUnit.NONE)
dg_meter_pt_ratio = ModbusRegister(200, 1, 3, ModbusType.U16, ModbusUnit.NONE)

# Meter Registers - PV Grid-tie Meter (220-260)
pv_meter_a_voltage = ModbusRegister(220, 2, 3, ModbusType.S32, ModbusUnit.VOLT, gain=0.1)
pv_meter_b_voltage = ModbusRegister(222, 2, 3, ModbusType.S32, ModbusUnit.VOLT, gain=0.1)
pv_meter_c_voltage = ModbusRegister(224, 2, 3, ModbusType.S32, ModbusUnit.VOLT, gain=0.1)
pv_meter_a_current = ModbusRegister(226, 2, 3, ModbusType.S32, ModbusUnit.AMPERE, gain=0.1)
pv_meter_b_current = ModbusRegister(228, 2, 3, ModbusType.S32, ModbusUnit.AMPERE, gain=0.1)
pv_meter_c_current = ModbusRegister(230, 2, 3, ModbusType.S32, ModbusUnit.AMPERE, gain=0.1)
pv_meter_frequency = ModbusRegister(232, 1, 3, ModbusType.U16, ModbusUnit.HERTZ, gain=0.001)
pv_meter_total_pf = ModbusRegister(233, 1, 3, ModbusType.S16, ModbusUnit.PF, gain=0.01)
pv_meter_a_active_power = ModbusRegister(234, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
pv_meter_b_active_power = ModbusRegister(236, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
pv_meter_c_active_power = ModbusRegister(238, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
pv_meter_a_apparent_power = ModbusRegister(240, 2, 3, ModbusType.S32, ModbusUnit.KVA, gain=0.1)
pv_meter_b_apparent_power = ModbusRegister(242, 2, 3, ModbusType.S32, ModbusUnit.KVA, gain=0.1)
pv_meter_c_apparent_power = ModbusRegister(244, 2, 3, ModbusType.S32, ModbusUnit.KVA, gain=0.1)
pv_meter_total_active_power = ModbusRegister(246, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
pv_meter_total_reactive_power = ModbusRegister(248, 2, 3, ModbusType.S32, ModbusUnit.KVAR, gain=0.1)
pv_meter_total_apparent_power = ModbusRegister(250, 2, 3, ModbusType.S32, ModbusUnit.KVA, gain=0.1)
pv_meter_positive_energy = ModbusRegister(252, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=0.01)
pv_meter_reverse_energy = ModbusRegister(254, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=0.01)
pv_meter_max_demand = ModbusRegister(256, 2, 3, ModbusType.U32, ModbusUnit.KW, gain=0.1)
pv_meter_comm_status = ModbusRegister(258, 1, 3, ModbusType.S16, ModbusUnit.NONE)
pv_meter_ct_ratio = ModbusRegister(259, 1, 3, ModbusType.S16, ModbusUnit.NONE)
pv_meter_pt_ratio = ModbusRegister(260, 1, 3, ModbusType.U16, ModbusUnit.NONE)