# Device Information Registers (10000-10999)
device_sn_n = "DeviceSn"

# Summary Registers (0-61)
work_mode_n = "WorkMode"
work_status_n = "WorkStatus"
system_total_rated_power_n = "SystemTotalRatedPower"
system_chargeable_energy_n = "SystemChargeableEnergy"
system_dischargeable_energy_n = "SystemDischargeableEnergy"
system_chargeable_power_n = "SystemChargeablePower"
system_dischargeable_power_n = "SystemDischargeablePower"
max_power_charge_available_time_n = "MaxPowerChargeAvailableTime"
max_power_discharge_available_time_n = "MaxPowerDischargeAvailableTime"
system_soc_n = "SystemSOC"
system_active_power_n = "SystemActivePower"
system_reactive_power_n = "SystemReactivePower"
system_total_charge_n = "SystemTotalCharge"
system_total_discharge_n = "SystemTotalDischarge"
system_daily_charge_n = "SystemDailyCharge"
system_daily_discharge_n = "SystemDailyDischarge"
available_reactive_power_n = "AvailableReactivePower"
total_power_generation_n = "TotalPowerGeneration"
daily_power_generation_n = "DailyPowerGeneration"
pv_installed_capacity_n = "PVInstalledCapacity"
pv_theoretical_active_power_n = "PVTheoreticalActivePower"
pv_available_active_power_n = "PVAvailableActivePower"
pv_available_reactive_power_n = "PVAvailableReactivePower"
pv_active_power_n = "PVActivePower"
pv_reactive_power_n = "PVReactivePower"
grid_side_load_total_power_n = "GridSideLoadTotalPower"
backup_side_load_total_power_n = "BackupSideLoadTotalPower"
total_load_power_n = "TotalLoadPower"
total_battery_power_n = "TotalBatteryPower"
platform_type_n = "PlatformType"
protocol_version_n = "ProtocolVersion"
dual_power_state_n = "DualPowerState"
system_mode_n = "SystemMode"
