from pyalpha.definition.models import ModbusRegister, ModbusType, ModbusUnit

device_sn = ModbusRegister(10000, 8, 3, ModbusType.STRING, ModbusUnit.NONE, gain=1)

# Summary Registers (function code 3, addresses 0-61)
work_mode = ModbusRegister(0, 1, 3, ModbusType.U16, ModbusUnit.NONE)
work_status = ModbusRegister(1, 1, 3, ModbusType.U16, ModbusUnit.NONE)
system_total_rated_power = ModbusRegister(2, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
system_chargeable_energy = ModbusRegister(4, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=0.1)
system_dischargeable_energy = ModbusRegister(6, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=0.1)
system_chargeable_power = ModbusRegister(8, 2, 3, ModbusType.U32, ModbusUnit.KW, gain=0.1)
system_dischargeable_power = ModbusRegister(10, 2, 3, ModbusType.U32, ModbusUnit.KW, gain=0.1)
max_power_charge_available_time = ModbusRegister(12, 1, 3, ModbusType.U16, ModbusUnit.MINUTE)
max_power_discharge_available_time = ModbusRegister(13, 1, 3, ModbusType.U16, ModbusUnit.MINUTE)
system_soc = ModbusRegister(14, 1, 3, ModbusType.U16, ModbusUnit.PERCENTAGE, gain=0.1)
system_active_power = ModbusRegister(19, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
system_reactive_power = ModbusRegister(21, 2, 3, ModbusType.S32, ModbusUnit.KVAR, gain=0.1)
system_total_charge = ModbusRegister(23, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=10)
system_total_discharge = ModbusRegister(25, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=10)
system_daily_charge = ModbusRegister(27, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=0.1)
system_daily_discharge = ModbusRegister(29, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=0.1)
available_reactive_power = ModbusRegister(31, 2, 3, ModbusType.U32, ModbusUnit.KVAR, gain=0.1)
total_power_generation = ModbusRegister(33, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=10)
daily_power_generation = ModbusRegister(35, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=0.1)
pv_installed_capacity = ModbusRegister(37, 2, 3, ModbusType.U32, ModbusUnit.KWH, gain=0.1)
pv_theoretical_active_power = ModbusRegister(39, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
pv_available_active_power = ModbusRegister(41, 2, 3, ModbusType.U32, ModbusUnit.KW, gain=0.1)
pv_available_reactive_power = ModbusRegister(43, 2, 3, ModbusType.U32, ModbusUnit.KVAR, gain=0.1)
pv_active_power = ModbusRegister(45, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
pv_reactive_power = ModbusRegister(47, 2, 3, ModbusType.S32, ModbusUnit.KVAR, gain=0.1)
grid_side_load_total_power = ModbusRegister(49, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
backup_side_load_total_power = ModbusRegister(51, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
total_load_power = ModbusRegister(53, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
total_battery_power = ModbusRegister(55, 2, 3, ModbusType.S32, ModbusUnit.KW, gain=0.1)
platform_type = ModbusRegister(57, 1, 3, ModbusType.U16, ModbusUnit.NONE)
protocol_version = ModbusRegister(58, 1, 3, ModbusType.U16, ModbusUnit.NONE)
dual_power_state = ModbusRegister(59, 1, 3, ModbusType.U16, ModbusUnit.NONE)
system_mode = ModbusRegister(60, 1, 3, ModbusType.U16, ModbusUnit.NONE)
